site_name: '万卷茅屋'
site_description: 'The documents of Werther Zhang'
copyright: 'Copyright &copy; 2018 Werther Zhang'
site_author: 'Werther Zhang'
site_url: 'https://pengzhangdev.github.io'

theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'light blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    language: 'zh'
    feature:
        tabs: true
    logo: 
        icon: 'whatshot'

extra:
    search:
        language: 'en, jp'
    social:
        - type: 'coding'
          link: 'http://wertherzhang.coding.me/'
        - type: 'netlify'
          link: 'https://pengzhang.netlify.com/'

google_analytics:
    - 'UA-XXXXXXXX-X'
    - 'auto'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: true
    - toc:
        permalink: true

pages:
    - 万卷茅屋: index.md
    - 关于: about.md

    - Android:
        - zram: zram.md
        - Android8分区表分析: android8-partiton-table.md
        - AB系统升级: Android-AB-system-update.md
        - Android内存调试总结: Android-memory-debug.md
        - Android SELinux 规则介绍: SEAndroid规则介绍.md
        - tcmalloc2.1 浅析 : tcmalloc2.1浅析.md
        - dlmalloc 浅析 : dlmalloc浅析.md

    - Python:
        - slackbot详细说明: slackbot.md

    - 存档:
        - Android内存调试总结: 2017-11-14-Android-memory-debug.md
        - slackbot详细说明: 2017-10-01-slackbot.md
        - AB系统升级: 2017-09-20-Android-AB-system-update.md
        - Android8分区表分析: 2017-09-19-android8-partiton-table.md
        - zram: 2017-08-22-zram.md
        - Android SELinux 规则介绍: 2016-12-12-SEAndroid规则介绍.md
        - tcmalloc2.1 浅析 : 2014-05-12-tcmalloc2.1浅析.md
        - dlmalloc 浅析 : 2014-03-05-dlmalloc浅析.md

